### ISSUE TITLE
TPM Error on Java NO_SESSIONS

### ISSUE THREAD

**Issue by eix128** [microsoft/TSS.MSR#164]
Exception in thread "main" tss.TpmException: Unexpected response tag {NO_SESSIONS}
	at tss.TpmBase.DispatchCommand(TpmBase.java:391)
	at tss.Tpm.ActivateCredential(Tpm.java:244)
	at samples.Samples.ek(Samples.java:534)
	at samples.Samples.doAll(Samples.java:56)
	at TSSMain.main(TSSMain.java:21)

Hi , i ve tried sample on microsoft tpm

These methods also dont work on my machine
//        getCapability();
//        pcr1();
//        primaryKeys();
//        childKeys();

Whats wrong ?

PS C:\WINDOWS\system32> Get-Tpm

TpmPresent                : True
TpmReady                  : True
TpmEnabled                : True
TpmActivated              : True
TpmOwned                  : True
RestartPending            : True
ManufacturerId            : 1229870147
ManufacturerIdTxt         : INTC
ManufacturerVersion       : 600.7.0.0
ManufacturerVersionFull20 : 600.7.0.0

ManagedAuthLevel          : Full
OwnerAuth                 : xxxxxxxxxxxxxx
OwnerClearDisabled        : False
AutoProvisioning          : Disabled
LockedOut                 : False
LockoutHealTime           : 10 minutes
LockoutCount              : 0
LockoutMax                : 31
SelfTest                  : {}

**Comment by hobo0cn** [comment]
Run with administrator privileges.

**Comment by ghostidentity** [comment]
I confirmed that the java library can work on infinion-based tpm  but dont use encryptDecrypt that is provided on the sample, use the RSA_Encrypt and RSA_Decrypt  instead

**Comment by Hcely** [comment]
Execute "  tpmtool gatherlogs C:\Users\Public " in Windows CMD.  System will export all info of TPM into TpmInformation.txt.  See  Tpm "Supported Commands". My computer not supported “tpm2_encryptdecrypt”，my other computer supported this commands.

<img width="1426" height="733" alt="Image" src="https://github.com/user-attachments/assets/04dbf992-b833-497a-bce3-9a6672a926ab" />

<img width="910" height="680" alt="Image" src="https://github.com/user-attachments/assets/3a90037f-094b-4731-b909-fcbf3c819e98" />
