### ISSUE TITLE
GetDuplicationBlob on linux

### ISSUE THREAD

**Issue by AndreArantes** [microsoft/TSS.MSR#71]
I'm trying to reproduce the import sample from TSS.NET Samples using .Net Core(3.0.102) on Linux, but when I try to use the function GetDuplicationBlob I got an error.
Precisely in this line `TpmPrivate dupBlob = swKey.GetDuplicationBlob(pubParent, innerWrapKey, out encSecret);`

> System.DllNotFoundException: Unable to load shared library 'bcrypt.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbcrypt.dll: cannot open shared object file: No such file or directory
   at Tpm2Lib.Native.BCryptOpenAlgorithmProvider(UIntPtr& AlgProvider, String AlgId, String Implementation, UInt32 Flags)
   at Tpm2Lib.BCryptAlgorithm.Open(String algName, UInt32 flags)
   at Tpm2Lib.BCryptAlgorithm..ctor(String algName, UInt32 flags)
   at Tpm2Lib.AsymCryptoSystem.EncryptOaep(Byte[] plainText, Byte[] label)
   at Tpm2Lib.TssObject.GetDuplicationBlob(TpmPublic pubNewParent, SymCipher innerWrapper, Byte[]& encSecret)
   at TpmAPI.Data.TpmFunctions.LoadExternalKey(SymDefObject innerSymDef) in /home/andre/Dev/TpmAPI/Data/TpmFunctions.cs:line 281
   at TpmAPI.Controllers.TpmController.LoadExternalKey() in /home/andre/Dev/TpmAPI/Controllers/TpmController.cs:line 71
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I didn't have any issues like that with the TSS.NET before. Is there any way to fix it?

**Comment by amarochk** [comment]
Are you sure you are using the latest version of TSS.Net? The code of EncryptOaep() should look like this:

``` C#
#if TSS_USE_BCRYPT
            var paddingInfo = new BCryptOaepPaddingInfo(OaepHash, label);
            byte[] cipherText = Key.Encrypt(plainText, paddingInfo);
#elif true
            var rr = new RawRsa(RsaProvider.ExportParameters(false), RsaProvider.KeySize);
            byte[] cipherText = rr.OaepEncrypt(plainText, OaepHash, label);
#else
            RSAParameters parms = RsaProvider.ExportParameters(false);
            var alg = new BCryptAlgorithm(Native.BCRYPT_RSA_ALGORITHM);
            var key = alg.LoadRSAKey(parms.Exponent, parms.Modulus);
            var paddingInfo = new BCryptOaepPaddingInfo(OaepHash, label);
            byte[] cipherText = key.Encrypt(plainText, paddingInfo);
            key.Destroy();
            alg.Close();
#endif
```

Essentially the branch using BCrypt is disabled now on Linux.

**Comment by AndreArantes** [comment]
I'm pretty sure I'm using the TSS.NET version 2.1.1 which I think is the last version.
`<PackageReference Include="Microsoft.TSS" Version="2.1.1" />`
But about that code how can I check it?

**Comment by amarochk** [comment]
I mean the latest version on github. There is no nuget package with this change yet.

**Comment by AndreArantes** [comment]
So I clone the repository and compiled the project using the command below:
`dotnet build TSS.Net.csproj -r linux-x64 -f netcoreapp2.0 -c Release `

> TSS.Net -> /home/andre/Dev/TSS.MSR/TSS.NET/bin/TSS.Net/Release/netcoreapp2.0/linux-x64/TSS.Net.dll

Then I add the package reference to my project:

```
<ItemGroup>
  <Reference Include="Microsoft.TSS">
	<HintPath>/home/andre/Dev/TSS.MSR/TSS.NET/bin/TSS.Net/Release/netcoreapp2.0/linux-x64/TSS.Net.dll</HintPath>
  </Reference>
</ItemGroup>
```
But I still get the same error mensage. Did I do something wrong?

> System.DllNotFoundException: Unable to load shared library 'bcrypt.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbcrypt.dll: cannot open shared object file: No such file or directory
   at Tpm2Lib.Native.BCryptOpenAlgorithmProvider(UIntPtr& AlgProvider, String AlgId, String Implementation, UInt32 Flags)
   at Tpm2Lib.BCryptAlgorithm.Open(String algName, UInt32 flags) in /home/andre/Dev/TSS.MSR/TSS.NET/TSS.Net/BCryptInterface.cs:line 408
   at Tpm2Lib.BCryptAlgorithm..ctor(String algName, UInt32 flags) in /home/andre/Dev/TSS.MSR/TSS.NET/TSS.Net/BCryptInterface.cs:line 399
   at Tpm2Lib.CryptoLib.HashData(TpmAlgId algId, Byte[] dataToHash) in /home/andre/Dev/TSS.MSR/TSS.NET/TSS.Net/CryptoLib.cs:line 34
   at Tpm2Lib.TpmHash.FromString(TpmAlgId hashAlg, String message) in /home/andre/Dev/TSS.MSR/TSS.NET/TSS.Net/TpmCustomDefs.cs:line 255
   at Tpm2Lib.AuthValue.FromString(TpmAlgId hashAlg, String password) in /home/andre/Dev/TSS.MSR/TSS.NET/TSS.Net/TpmCustomDefs.cs:line 369
   at TpmAPI.Data.TpmFunctions.LoadExternalKey(SymDefObject innerSymDef) in /home/andre/Dev/TpmAPI/Data/TpmFunctions.cs:line 268
   at TpmAPI.Controllers.TpmController.LoadExternalKey() in /home/andre/Dev/TpmAPI/Controllers/TpmController.cs:line 71
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by amarochk** [comment]
Well, the failure is at the different place this time. And you should not have been able to get there, as the failure point is in the `#if TSS_USE_BCRYPT` branch, and `TSS_USE_BCRYPT` is not defined in Linux builds of TSS.Net...

I'll try to reproduce it, and see what's going on...

**Comment by amarochk** [comment]
Well, somehow a wrong macro name slipped into the NetCore branch of the TSS.Net project file recently. I've just committed the fix. Please see if it works for you now. And thank you for reporting the problem!

**Comment by AndreArantes** [comment]
Looks like it finally works, thank you so much for your attention, hope this helped!
