### ISSUE TITLE
SignerCallback not called when running a policy

### ISSUE THREAD

**Issue by rhegner** [microsoft/TSS.MSR#80]
Here's what I'm trying to do:

1. Create a policy containing `TpmPolicySigned`
2. Serialize the policy (which serializes only the public part of the key)
3. Deserialize the policy
4. Run the deserialized policy and expecting to get a call to the signer callback.

But my signer callback never gets called - instead I get a `NullReferenceException` at

```
   at Tpm2Lib.BCryptObject.op_Implicit(BCryptObject key)
   at Tpm2Lib.AsymCryptoSystem.SignData(Byte[] data, TpmAlgId sigHash)
   at Tpm2Lib.AsymCryptoSystem.Sign(Byte[] data)
   at Tpm2Lib.TpmPolicySigned.Execute(Tpm2 tpm, AuthSession sess, PolicyTree policy)
   at Tpm2Lib.AuthSession.RunPolicy(Tpm2 tpm, PolicyTree policyTree, String branchToEvaluate, Boolean allowErrors)
```

I think the problem is in the library at
https://github.com/microsoft/TSS.MSR/blob/f0afe4e9e140b892fe41aff25501b58711856b22/TSS.NET/TSS.Net/PolicyAces.cs#L874

The code checks if there is a key available, but it should more specifically check if there is a private key available, and otherwise invoke the sign callback.

Or maybe there is a misunderstanding on my side? (I'm still in the middle of learning TPM and TSS.MSR)

I do have another question which is not directly related to the above: How can I create a `System.Security.Cryptography.RSA` object from a `AsymCryptoSystem` and vice versa?

**Comment by rhegner** [comment]
I found a workaround. When creating the policy I'm now using the overload of `TpmPolicySigned` which takes a byte array as its first argument.

This works:

    new TpmPolicySigned(key.GetPublicParms().GetName(), ...)

instead of:

    new TpmPolicySigned(key, ...)
